appname: *
version: *

handle:

#URL重写
- rewrite: if( !is_file() && path ~ "/admin/" ) goto "/admin/index.php?%{QUERY_STRING}"
- rewrite: if( !is_file() && path ~ "/install/" ) goto "/install/index.php?%{QUERY_STRING}"
- rewrite: if( !is_file() ) goto "index.php?%{QUERY_STRING}"